[project]
name = 'QvaPayUSD'
description = 'QUSD is a stablecoin that is pegged to the US dollar and is fully compliant with the SIP-010 standard for QvaPay treasury.'
authors = ['n3omaster']
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
[contracts.QUSD]
path = 'contracts/QUSD.clar'
clarity_version = 3
epoch = 3.1

[contracts.qusd-notifier]
path = 'contracts/qusd-notifier.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
