[project]
name = 'QUSD'
description = 'QUSD is a stablecoin that is pegged to the US dollar and is fully compliant with the SIP-010 standard for QvaPay treasury internal use.'
authors = ['n3omaster']
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'
[contracts.QUSD]
path = 'contracts/QUSD.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
